#!/usr/bin/env sh

wget -qO- https://api.github.com/repos/docker/compose/releases/latest \
| grep `uname -s`-`uname -m` \
| grep -v "sha256" \
| cut -d : -f 2,3 \
| tr -d \" \
| wget -i - -O /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
echo 'You can now type docker-compose to use Docker Compose'