#!/usr/bin/env sh

wget -qO- https://api.github.com/repos/jesseduffield/lazygit/releases/latest \
| grep `uname -s`_`uname -m` \
| cut -d : -f 2,3 \
| tr -d \" \
| wget -i - -O /tmp/lazygit.tar.gz
rm -rf /opt/lazygit
mkdir /opt/lazygit
tar -xf /tmp/lazygit.tar.gz -C /opt/lazygit/
ln -fs /opt/lazygit/lazygit /usr/local/bin/lazygit
rm /tmp/lazygit.tar.gz
echo 'You can now type lazygit to start lazygit'