#!/usr/bin/env sh

wget https://telegram.org/dl/desktop/linux -O /tmp/telegram.tar.xz
tar -xf /tmp/telegram.tar.xz -C /opt/
ln -fs /opt/Telegram/Telegram /usr/local/bin/telegram-desktop
rm /tmp/telegram.tar.xz
echo 'You can now type telegram-desktop to start Telegram'